-- =====================================================================
-- schema.sql - the trading_system_db schema: tables, migrations 001-016, indexes
--
-- GENERATED by scripts/build-db-scripts.sh from the files named below,
-- in this order. Edit those, not this file, then run the script again.
-- =====================================================================

-- ---------------------------------------------------------------------
-- base/000_base_schema.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- 000_base_schema.sql
-- =====================================================================

-- ---------------------------------------------------------------------
-- CLIENT_ACCOUNT : trading identity, KYC state and money balances.
-- Grain: one row per client.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS client_account (
    client_id       INTEGER      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    pan             VARCHAR(10)  NOT NULL UNIQUE,
    demat_id        VARCHAR(16)  NOT NULL UNIQUE,
    kyc_status      VARCHAR(10)  NOT NULL DEFAULT 'PENDING',
    balance         NUMERIC(18,4) NOT NULL DEFAULT 0,
    blocked_funds   NUMERIC(18,4) NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_client_account_kyc_status
        CHECK (kyc_status IN ('PENDING', 'VERIFIED', 'REJECTED')),
    CONSTRAINT ck_client_account_balance_non_negative
        CHECK (balance >= 0),
    CONSTRAINT ck_client_account_blocked_non_negative
        CHECK (blocked_funds >= 0),
    CONSTRAINT ck_client_account_blocked_within_balance
        CHECK (blocked_funds <= balance)
);

-- ---------------------------------------------------------------------
-- CLIENT_PROFILE : personal / KYC-visible details. 1:1 with account.
-- Grain: one row per client.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS client_profile (
    client_id       INTEGER      PRIMARY KEY
                                 REFERENCES client_account (client_id),
    name            VARCHAR(120) NOT NULL,
    dob             DATE         NOT NULL,
    email           VARCHAR(200) NOT NULL UNIQUE,
    phone_number    VARCHAR(20)  NOT NULL,
    address         TEXT
);

-- ---------------------------------------------------------------------
-- CLIENT_AUTH : login credentials. 1:1 with account.
-- Grain: one row per client.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS client_auth (
    client_id       INTEGER      PRIMARY KEY
                                 REFERENCES client_account (client_id),
    password_hash   VARCHAR(255) NOT NULL,
    last_login      TIMESTAMPTZ
);

-- ---------------------------------------------------------------------
-- FUND_TRANSFER : deposits and withdrawals via the payment gateway.
-- Grain: one row per money-movement attempt.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fund_transfer (
    transfer_id     BIGINT       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    client_id       INTEGER      NOT NULL
                                 REFERENCES client_account (client_id),
    amount          NUMERIC(18,4) NOT NULL,
    direction       VARCHAR(10)  NOT NULL,
    status          VARCHAR(10)  NOT NULL DEFAULT 'PENDING',
    reference_id    VARCHAR(100),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_fund_transfer_direction
        CHECK (direction IN ('DEPOSIT', 'WITHDRAWAL')),
    CONSTRAINT ck_fund_transfer_status
        CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED')),
    CONSTRAINT ck_fund_transfer_amount_positive
        CHECK (amount > 0)
);

-- ---------------------------------------------------------------------
-- EXCHANGE : trading venue reference data.
-- Grain: one row per exchange.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS exchange (
    exchange_code   VARCHAR(10)  PRIMARY KEY,
    name            VARCHAR(120) NOT NULL,
    country         CHAR(2)      NOT NULL DEFAULT 'IN',
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE
);

-- ---------------------------------------------------------------------
-- AMC : asset management company (mutual fund house).
-- Grain: one row per fund house.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS amc (
    amc_id          INTEGER      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    amc_code        VARCHAR(20)  NOT NULL UNIQUE,
    amc_name        VARCHAR(120) NOT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE
);

-- ---------------------------------------------------------------------
-- INSTRUMENT : supertype for everything tradeable on the platform.
-- Subtypes (equity / mutual_fund) share this primary key.
--
-- The UNIQUE (instrument_id, instrument_type) below is redundant as a
-- uniqueness rule - instrument_id is already the PK - but it exists to
-- be the target of a composite FK from each subtype, which is what
-- makes subtype disjointness enforceable by the database.
-- Grain: one row per tradeable security.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS instrument (
    instrument_id   INTEGER      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    instrument_type VARCHAR(10)  NOT NULL,
    name            VARCHAR(200) NOT NULL,
    isin            VARCHAR(12)  NOT NULL UNIQUE,

    CONSTRAINT ck_instrument_type
        CHECK (instrument_type IN ('STOCK', 'ETF', 'MF')),
    CONSTRAINT uq_instrument_id_type
        UNIQUE (instrument_id, instrument_type)
);

-- ---------------------------------------------------------------------
-- EQUITY : subtype of instrument for exchange-traded scrips
-- (stocks and ETFs). PK is also FK to the parent.
-- Grain: one row per exchange-traded instrument.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS equity (
    instrument_id   INTEGER      PRIMARY KEY
                                 REFERENCES instrument (instrument_id),
    instrument_type VARCHAR(10)  NOT NULL,
    ticker          VARCHAR(30)  NOT NULL,
    exchange_code   VARCHAR(10)  NOT NULL
                                 REFERENCES exchange (exchange_code),
    lot_size        INTEGER      NOT NULL DEFAULT 1,

    CONSTRAINT ck_equity_instrument_type
        CHECK (instrument_type IN ('STOCK', 'ETF')),
    CONSTRAINT fk_equity_instrument_type
        FOREIGN KEY (instrument_id, instrument_type)
        REFERENCES instrument (instrument_id, instrument_type),
    CONSTRAINT ck_equity_lot_size_positive
        CHECK (lot_size > 0),
    CONSTRAINT uq_equity_ticker_exchange
        UNIQUE (ticker, exchange_code)
);

-- ---------------------------------------------------------------------
-- MUTUAL_FUND : subtype of instrument for MF schemes.
-- PK is also FK to the parent. Same composite-FK pattern as EQUITY.
-- Grain: one row per MF scheme.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mutual_fund (
    instrument_id   INTEGER      PRIMARY KEY
                                 REFERENCES instrument (instrument_id),
    instrument_type VARCHAR(10)  NOT NULL,
    scheme_code     VARCHAR(30)  NOT NULL UNIQUE,
    amc_id          INTEGER      NOT NULL
                                 REFERENCES amc (amc_id),
    plan_type       VARCHAR(20)  NOT NULL,
    expense_ratio   NUMERIC(5,4),

    CONSTRAINT ck_mutual_fund_instrument_type
        CHECK (instrument_type = 'MF'),
    CONSTRAINT fk_mutual_fund_instrument_type
        FOREIGN KEY (instrument_id, instrument_type)
        REFERENCES instrument (instrument_id, instrument_type),
    CONSTRAINT ck_mutual_fund_plan_type
        CHECK (plan_type IN ('DIRECT_GROWTH', 'DIRECT_IDCW',
                             'REGULAR_GROWTH', 'REGULAR_IDCW')),
    CONSTRAINT ck_mutual_fund_expense_ratio
        CHECK (expense_ratio IS NULL OR expense_ratio >= 0)
);

-- ---------------------------------------------------------------------
-- ORDERS : live and recent orders.
-- Terminal rows are archived to orders_history by the EOD job.
-- Grain: one row per order placed by a client.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
    order_id           BIGINT       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    client_id          INTEGER      NOT NULL
                                    REFERENCES client_account (client_id),
    instrument_id      INTEGER      NOT NULL
                                    REFERENCES instrument (instrument_id),
    side               VARCHAR(4)   NOT NULL,
    order_type         VARCHAR(10)  NOT NULL,
    product_type       VARCHAR(3)   NOT NULL,
    price              NUMERIC(18,4),
    quantity           NUMERIC(18,6) NOT NULL,
    filled_quantity    NUMERIC(18,6) NOT NULL DEFAULT 0,
    average_fill_price NUMERIC(18,4),
    status             VARCHAR(10)  NOT NULL DEFAULT 'PENDING',
    date_placed        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_updated       TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_orders_side
        CHECK (side IN ('BUY', 'SELL')),
    CONSTRAINT ck_orders_order_type
        CHECK (order_type IN ('MARKET', 'LIMIT')),
    CONSTRAINT ck_orders_product_type
        CHECK (product_type IN ('MIS', 'CNC')),
    CONSTRAINT ck_orders_status
        CHECK (status IN ('PENDING', 'PARTIAL', 'SUCCESS',
                          'FAILED', 'CANCELLED')),
    CONSTRAINT ck_orders_quantity_positive
        CHECK (quantity > 0),
    CONSTRAINT ck_orders_limit_needs_price
        CHECK (order_type <> 'LIMIT' OR price IS NOT NULL)
);

-- ---------------------------------------------------------------------
-- ORDERS_HISTORY : archive of terminal orders.
-- Grain: one row per archived order.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders_history (
    order_id           BIGINT       PRIMARY KEY,
    client_id          INTEGER      NOT NULL
                                    REFERENCES client_account (client_id),
    instrument_id      INTEGER      NOT NULL
                                    REFERENCES instrument (instrument_id),
    side               VARCHAR(4)   NOT NULL,
    order_type         VARCHAR(10)  NOT NULL,
    product_type       VARCHAR(3)   NOT NULL,
    price              NUMERIC(18,4),
    quantity           NUMERIC(18,6) NOT NULL,
    filled_quantity    NUMERIC(18,6) NOT NULL DEFAULT 0,
    average_fill_price NUMERIC(18,4),
    status             VARCHAR(10)  NOT NULL,
    date_placed        TIMESTAMPTZ  NOT NULL,
    last_updated       TIMESTAMPTZ  NOT NULL,
    archived_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_orders_history_side
        CHECK (side IN ('BUY', 'SELL')),
    CONSTRAINT ck_orders_history_order_type
        CHECK (order_type IN ('MARKET', 'LIMIT')),
    CONSTRAINT ck_orders_history_product_type
        CHECK (product_type IN ('MIS', 'CNC')),
    CONSTRAINT ck_orders_history_status
        CHECK (status IN ('SUCCESS', 'FAILED', 'CANCELLED'))
);

-- ---------------------------------------------------------------------
-- POSITION : current holdings. INTRADAY rows feed the Positions tab, DELIVERY rows the Holdings tab. Deliberately has no FK to orders: a holding outlives the (archived) order that created it.
-- Grain: one row per client per instrument per position type.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS position (
    position_id     BIGINT       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    client_id       INTEGER      NOT NULL
                                 REFERENCES client_account (client_id),
    instrument_id   INTEGER      NOT NULL
                                 REFERENCES instrument (instrument_id),
    position_type   VARCHAR(10)  NOT NULL,
    quantity        NUMERIC(18,6) NOT NULL,
    average_price   NUMERIC(18,4) NOT NULL,

    CONSTRAINT ck_position_type
        CHECK (position_type IN ('INTRADAY', 'DELIVERY')),
    CONSTRAINT ck_position_quantity_positive
        CHECK (quantity > 0),
    CONSTRAINT ck_position_average_price_positive
        CHECK (average_price > 0),
    CONSTRAINT uq_position_client_instrument_type
        UNIQUE (client_id, instrument_id, position_type)
);


-- ---------------------------------------------------------------------
-- Correctness constraint, not a performance index.
-- ---------------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS uq_fund_transfer_reference_id
    ON fund_transfer (reference_id)
    WHERE reference_id IS NOT NULL;

-- ---------------------------------------------------------------------
-- migrations/001_schema_migrations.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- 001_schema_migrations.sql
-- =====================================================================

-- ---------------------------------------------------------------------
-- status gates behaviour:
--  ACTIVE, SUSPENDED, CLOSED 
-- ---------------------------------------------------------------------
ALTER TABLE client_account
    ADD COLUMN IF NOT EXISTS status  VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN IF NOT EXISTS version INTEGER     NOT NULL DEFAULT 0;

ALTER TABLE client_account
    DROP CONSTRAINT IF EXISTS ck_client_account_status;

ALTER TABLE client_account
    ADD CONSTRAINT ck_client_account_status
        CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CLOSED'));

ALTER TABLE client_account
    DROP CONSTRAINT IF EXISTS ck_client_account_version_non_negative;

ALTER TABLE client_account
    ADD CONSTRAINT ck_client_account_version_non_negative
        CHECK (version >= 0);

-- ---------------------------------------------------------------------
-- 3. Tradability flag on the instrument supertype only.
--
-- is_tradable = FALSE means: hidden from search, no new orders accepted.
-- Existing positions in the instrument remain valid and visible, so a
-- client holding a delisted scrip still sees it in Holdings.
-- ---------------------------------------------------------------------
ALTER TABLE instrument
    ADD COLUMN IF NOT EXISTS is_tradable BOOLEAN NOT NULL DEFAULT TRUE;

-- ---------------------------------------------------------------------
-- 4. Remove the PARTIAL fill concept from ORDERS.
-- ---------------------------------------------------------------------
ALTER TABLE orders
    DROP COLUMN IF EXISTS filled_quantity;

ALTER TABLE orders
    RENAME COLUMN average_fill_price TO fill_price;

ALTER TABLE orders
    RENAME COLUMN last_updated TO resolved_at;

ALTER TABLE orders
    ALTER COLUMN resolved_at DROP NOT NULL,
    ALTER COLUMN resolved_at DROP DEFAULT;

ALTER TABLE orders
    DROP CONSTRAINT IF EXISTS ck_orders_status;

ALTER TABLE orders
    ADD CONSTRAINT ck_orders_status
        CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED'));

-- A resolved order must carry its resolution timestamp; a pending one
-- must not. A successful order must carry the price it filled at.
ALTER TABLE orders
    DROP CONSTRAINT IF EXISTS ck_orders_resolved_at_matches_status;

ALTER TABLE orders
    ADD CONSTRAINT ck_orders_resolved_at_matches_status
        CHECK (
            (status = 'PENDING' AND resolved_at IS NULL)
            OR (status <> 'PENDING' AND resolved_at IS NOT NULL)
        );

ALTER TABLE orders
    DROP CONSTRAINT IF EXISTS ck_orders_success_needs_fill_price;

ALTER TABLE orders
    ADD CONSTRAINT ck_orders_success_needs_fill_price
        CHECK (status <> 'SUCCESS' OR fill_price IS NOT NULL);

-- ORDERS_HISTORY must stay column-identical to ORDERS, otherwise the
-- archival job breaks.
ALTER TABLE orders_history
    DROP COLUMN IF EXISTS filled_quantity;

ALTER TABLE orders_history
    RENAME COLUMN average_fill_price TO fill_price;

ALTER TABLE orders_history
    RENAME COLUMN last_updated TO resolved_at;

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(64);

ALTER TABLE orders_history
    ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(64);

ALTER TABLE fund_transfer
    ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(64);

CREATE UNIQUE INDEX IF NOT EXISTS uq_orders_client_idempotency_key
    ON orders (client_id, idempotency_key);

CREATE UNIQUE INDEX IF NOT EXISTS uq_orders_history_client_idempotency_key
    ON orders_history (client_id, idempotency_key);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fund_transfer_client_idempotency_key
    ON fund_transfer (client_id, idempotency_key);

-- ---------------------------------------------------------------------
-- migrations/002_api_alignment.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- 002_api_alignment.sql
--
-- Sprint 6. Aligns the schema with Contracts/API Schemas/trade-api.yaml, which the
-- Trade REST API implements and from which Sprint 9 generates its
-- Angular client.
--
-- Four changes, each with a reason:
--
--   1. orders.order_id and orders_history.order_id become UUID.
--   2. Order status literals become the contract's.
--   3. order_type and product_type get defaults.
--   4. client_account gains the string business reference the contract
--      calls AccountResponse.accountId.
--
-- Idempotent where it can be, so a re-run on an already-migrated
-- database is a no-op rather than an error.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. Order identity: BIGINT identity -> UUID.
--
-- WHY. The domain generates an order's identity in Order.place(),
-- before any database round-trip, which is what lets the rules be
-- tested with plain objects and lets a retry carry the identity it was
-- given. An identity column can only answer AFTER the insert, so the
-- domain would have to hold an order with no id until the row came
-- back, and the Trade Executor in Sprint 7 would have no id to put on
-- a Kafka event until the same round-trip had happened.
--
-- COST, stated so it can be argued with: 16 bytes per row instead of 8,
-- which at the year-7 volume in DESIGN.md (87.5M archived orders) is
-- roughly 0.7 GB more across table and index, and the loss of a
-- chronologically ordered primary key. The second matters less than it
-- looks: every query that wants recent orders goes through
-- ix_orders_client_placed on date_placed, not through the PK.
--
-- Both tables must move together. DESIGN.md requires orders_history to
-- stay column-identical to orders, because the archival job copies rows
-- between them by position.
-- ---------------------------------------------------------------------

-- gen_random_uuid() is built in from PostgreSQL 13. The extension is a
-- no-op there and the fallback for anything older.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'orders'
          AND column_name = 'order_id'
          AND data_type <> 'uuid'
    ) THEN
        -- Existing rows keep a row, not their number: the old BIGINT is
        -- discarded and a fresh UUID minted. Nothing outside these two
        -- tables references order_id -- position deliberately has no FK
        -- to orders, because a holding outlives the archived order that
        -- created it -- so no foreign key has to be rewritten.
        ALTER TABLE orders ADD COLUMN order_uuid UUID NOT NULL DEFAULT gen_random_uuid();
        ALTER TABLE orders DROP CONSTRAINT orders_pkey;
        ALTER TABLE orders DROP COLUMN order_id;   -- drops the identity sequence with it
        ALTER TABLE orders RENAME COLUMN order_uuid TO order_id;
        ALTER TABLE orders ALTER COLUMN order_id DROP DEFAULT;
        ALTER TABLE orders ADD CONSTRAINT orders_pkey PRIMARY KEY (order_id);
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'orders_history'
          AND column_name = 'order_id'
          AND data_type <> 'uuid'
    ) THEN
        ALTER TABLE orders_history ADD COLUMN order_uuid UUID NOT NULL DEFAULT gen_random_uuid();
        ALTER TABLE orders_history DROP CONSTRAINT orders_history_pkey;
        ALTER TABLE orders_history DROP COLUMN order_id;
        ALTER TABLE orders_history RENAME COLUMN order_uuid TO order_id;
        ALTER TABLE orders_history ALTER COLUMN order_id DROP DEFAULT;
        ALTER TABLE orders_history ADD CONSTRAINT orders_history_pkey PRIMARY KEY (order_id);
    END IF;
END $$;

-- The application supplies the id on every insert. A default here would
-- silently paper over a bug in which it forgot to.


-- ---------------------------------------------------------------------
-- 2. Order status literals.
--
-- WHY. AccountStatus, OrderSide and OrderStatus are fixed by the
-- contract, the database stores the same strings, and Sprint 9
-- generates its TypeScript from that file. The base schema predates the
-- contract and used the black box's vocabulary. One of the two had to
-- move, and the enum appears in three places against the schema's one.
--
--   PENDING   -> NEW        the working state
--   SUCCESS   -> FILLED     there is no partial fill; an order fills in
--                           full or is rejected
--   FAILED    -> REJECTED
--   CANCELLED -> CANCELLED  unchanged, and spelled with two Ls
--
-- Existing rows are translated before the constraint is tightened,
-- otherwise the ALTER fails on its own data.
-- ---------------------------------------------------------------------

ALTER TABLE orders           DROP CONSTRAINT IF EXISTS ck_orders_status;
ALTER TABLE orders_history   DROP CONSTRAINT IF EXISTS ck_orders_history_status;
ALTER TABLE orders           DROP CONSTRAINT IF EXISTS ck_orders_resolved_at_matches_status;
ALTER TABLE orders           DROP CONSTRAINT IF EXISTS ck_orders_success_needs_fill_price;

UPDATE orders SET status = CASE status
    WHEN 'PENDING' THEN 'NEW'
    WHEN 'SUCCESS' THEN 'FILLED'
    WHEN 'FAILED'  THEN 'REJECTED'
    ELSE status
END WHERE status IN ('PENDING', 'SUCCESS', 'FAILED');

UPDATE orders_history SET status = CASE status
    WHEN 'SUCCESS' THEN 'FILLED'
    WHEN 'FAILED'  THEN 'REJECTED'
    ELSE status
END WHERE status IN ('SUCCESS', 'FAILED');

ALTER TABLE orders
    ALTER COLUMN status SET DEFAULT 'NEW';

ALTER TABLE orders
    ADD CONSTRAINT ck_orders_status
        CHECK (status IN ('NEW', 'FILLED', 'REJECTED', 'CANCELLED'));

-- History holds terminal rows only. NEW is absent on purpose: an order
-- still working has not finished and must not be archived.
ALTER TABLE orders_history
    ADD CONSTRAINT ck_orders_history_status
        CHECK (status IN ('FILLED', 'REJECTED', 'CANCELLED'));

-- A resolved order carries its resolution timestamp; a working one must
-- not. Same rule as 001, restated over the new literal.
ALTER TABLE orders
    ADD CONSTRAINT ck_orders_resolved_at_matches_status
        CHECK (
            (status =  'NEW' AND resolved_at IS NULL)
         OR (status <> 'NEW' AND resolved_at IS NOT NULL)
        );

-- A filled order carries the price it filled at. A rejected or
-- cancelled one never does, which is why this is an implication and not
-- a NOT NULL.
ALTER TABLE orders
    ADD CONSTRAINT ck_orders_fill_price_matches_status
        CHECK (status <> 'FILLED' OR fill_price IS NOT NULL);

ALTER TABLE orders_history
    DROP CONSTRAINT IF EXISTS ck_orders_history_fill_price_matches_status;

ALTER TABLE orders_history
    ADD CONSTRAINT ck_orders_history_fill_price_matches_status
        CHECK (status <> 'FILLED' OR fill_price IS NOT NULL);


-- ---------------------------------------------------------------------
-- 3. Defaults for order_type and product_type.
--
-- WHY. Both are NOT NULL and neither has a field in PlaceOrderRequest,
-- whose six fields are fixed by the contract. Without a default no
-- order the API accepts can be inserted at all.
--
-- MARKET is the default because of what the customer actually does: on
-- the Sprint 9 screen, buying is one click. Requiring a limit price
-- before an order can be placed would make the common path the harder
-- one. The price the customer submits travels with the order as a
-- ceiling on a buy and a floor on a sell -- ck_orders_limit_needs_price
-- constrains LIMIT orders to carry one and says nothing about MARKET
-- orders that do.
--
-- CNC (delivery) is the default because an intraday position is squared
-- off the same evening by a job that does not exist yet. Every position
-- this service creates is therefore DELIVERY, and the Positions tab
-- stays empty until MIS is offered.
--
-- Both are defaults rather than dropped columns: the Trade Executor and
-- the Sprint 10 extensions will set them explicitly, and the black box
-- already distinguishes them.
-- ---------------------------------------------------------------------

ALTER TABLE orders
    ALTER COLUMN order_type   SET DEFAULT 'MARKET',
    ALTER COLUMN product_type SET DEFAULT 'CNC';


-- ---------------------------------------------------------------------
-- 4. The account business reference.
--
-- WHY. The contract's AccountResponse.accountId is the one place in the
-- platform where that name means a string rather than the numeric key.
-- It is what a customer reads off a statement and quotes to support,
-- and it is deliberately not the primary key: a support call should not
-- be able to guess the next account by adding one, and the surrogate
-- key should be free to change representation without a customer ever
-- seeing it.
--
-- Backfilled deterministically from client_id for the existing rows so
-- the seed data stays legible in a review. A real onboarding flow would
-- mint these from a non-sequential source.
-- ---------------------------------------------------------------------

ALTER TABLE client_account
    ADD COLUMN IF NOT EXISTS account_ref VARCHAR(20);

UPDATE client_account
    SET account_ref = 'ACC-' || lpad(client_id::text, 6, '0')
    WHERE account_ref IS NULL;

ALTER TABLE client_account
    ALTER COLUMN account_ref SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_client_account_ref
    ON client_account (account_ref);

-- ---------------------------------------------------------------------
-- migrations/003_account_last_updated.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- 003_account_last_updated.sql
--
-- AccountResponse.lastUpdated is a required field of the binding
-- contract, and client_account carried only created_at.
--
-- It is maintained by a trigger rather than by the application. Every
-- write to this row already goes through the optimistic lock, and there
-- are two of them today with more coming in Sprint 7 -- a timestamp set
-- in Java is one that a future writer forgets to set, and the field it
-- silently stops updating is the one a client uses to decide whether
-- its cached view is stale.
-- =====================================================================

ALTER TABLE client_account
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- Existing rows have never been written since creation, so their last
-- update genuinely is their creation.
UPDATE client_account
    SET updated_at = created_at
    WHERE updated_at < created_at;

CREATE OR REPLACE FUNCTION touch_client_account_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_client_account_updated_at ON client_account;

CREATE TRIGGER tr_client_account_updated_at
    BEFORE UPDATE ON client_account
    FOR EACH ROW
    EXECUTE FUNCTION touch_client_account_updated_at();

-- ---------------------------------------------------------------------
-- migrations/004_execution_columns.sql
-- ---------------------------------------------------------------------
-- 004_execution_columns.sql
--
-- Sprint 7. Adds the one column the executor writes that the schema did
-- not have. fill_price and resolved_at already exist, added by 001 under
-- our own names rather than the brief's executed_price / executed_on.
--
-- Idempotent, like 001 to 003.

-- The rejection reason. A column rather than a log line: it is the first
-- thing a customer asks about, and the analytics load reads it.
--
-- VARCHAR rather than an enum type, because the event contract types the
-- matching field as a free string so a new reason stays additive.

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS rejection_reason VARCHAR(40);

-- orders_history stays column-identical: the archival job copies by position.
ALTER TABLE orders_history
    ADD COLUMN IF NOT EXISTS rejection_reason VARCHAR(40);

-- A reason belongs only to an order that did not fill. NULL stays legal
-- for every status.

ALTER TABLE orders
DROP CONSTRAINT IF EXISTS ck_orders_reason_matches_status;

ALTER TABLE orders
    ADD CONSTRAINT ck_orders_reason_matches_status
        CHECK (rejection_reason IS NULL
            OR status IN ('REJECTED', 'CANCELLED'));

ALTER TABLE orders_history
DROP CONSTRAINT IF EXISTS ck_orders_history_reason_matches_status;

ALTER TABLE orders_history
    ADD CONSTRAINT ck_orders_history_reason_matches_status
        CHECK (rejection_reason IS NULL
            OR status IN ('REJECTED', 'CANCELLED'));

-- Finds orders the executor has not resolved, for the replay path.
-- Partial, because NEW is a small and short-lived minority.

CREATE INDEX IF NOT EXISTS ix_orders_unresolved
    ON orders (date_placed)
    WHERE status = 'NEW';
-- ---------------------------------------------------------------------
-- migrations/005_drop_client_auth.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- 005_drop_client_auth.sql
--
-- Sprint 8 moved credentials into the auth service, which owns the only
-- store in the platform that ever sees one. client_auth has had no
-- reader since: no Java, no mapper, and nothing holds a foreign key to
-- it. Leaving it means the database the Trade REST API connects to
-- still holds a table of password hashes, which is the arrangement
-- Sprint 8 exists to remove.
--
-- The hashes in it were never real. The seed says so: structurally
-- valid bcrypt strings, test data only.
-- =====================================================================

DROP TABLE IF EXISTS client_auth;

-- ---------------------------------------------------------------------
-- migrations/006_activation_email.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- 006_activation_email.sql
--
-- One row per ACCOUNT_PROVISIONED event the activation mailer has sent an
-- email for. Kafka delivers at least once, so the same event arrives twice
-- eventually; the event id is the idempotency key, and a second delivery
-- that finds its row sends nothing.
--
-- No email address and no token: this table records THAT an email went, not
-- what was in it.
-- =====================================================================

CREATE TABLE IF NOT EXISTS activation_email (
    event_id    UUID         PRIMARY KEY,
    client_id   INTEGER      NOT NULL REFERENCES client_account (client_id),
    sent_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- migrations/007_kyc.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- 007_kyc.sql
--
-- KYC: one verification per customer, and the outbox that announces a
-- pass on kyc-events.
--
-- kyc_verification is keyed by client_id, so a customer has exactly one.
-- That makes submission idempotent and resubmission impossible, which is
-- the decision: REJECTED is terminal. The check constraints hold the shape
-- of a decision in the database rather than in code -- a decided row
-- carries its time, and only a rejection carries a reason.
--
-- No personal data here. The checks are read from client_profile and
-- client_account when they run; this table records the outcome only.
-- =====================================================================

CREATE TABLE IF NOT EXISTS kyc_verification (
    client_id     INTEGER      PRIMARY KEY
                               REFERENCES client_account (client_id),
    status        VARCHAR(10)  NOT NULL DEFAULT 'PENDING',
    -- Set on REJECTED, and only then.
    reason        TEXT         NULL,
    -- Which checks ran and which failed, for the audit trail.
    checks        JSONB        NULL,
    submitted_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    decided_at    TIMESTAMPTZ  NULL,

    CONSTRAINT ck_kyc_verification_status
        CHECK (status IN ('PENDING', 'VERIFIED', 'REJECTED')),
    CONSTRAINT ck_kyc_verification_decided_at
        CHECK ((status = 'PENDING') = (decided_at IS NULL)),
    CONSTRAINT ck_kyc_verification_reason
        CHECK ((status = 'REJECTED') = (reason IS NOT NULL))
);

-- The scheduled job's only query: pending checks, oldest first.
CREATE INDEX IF NOT EXISTS ix_kyc_verification_pending
    ON kyc_verification (submitted_at) WHERE status = 'PENDING';

-- Events waiting to be published, written in the same transaction as the
-- change they announce: a rolled-back decision leaves no row and publishes
-- nothing, and a committed one is retried until the broker takes it. Same
-- shape as the auth service's outbox_event, which lives in its own database.
CREATE TABLE IF NOT EXISTS outbox_event (
    event_id      UUID         PRIMARY KEY,
    topic         VARCHAR(249) NOT NULL,
    message_key   VARCHAR(64)  NOT NULL,
    -- The whole envelope, exactly as it goes on the wire.
    envelope      JSONB        NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    published_at  TIMESTAMPTZ  NULL,
    attempts      INTEGER      NOT NULL DEFAULT 0,
    last_error    TEXT         NULL
);

CREATE INDEX IF NOT EXISTS ix_outbox_event_unpublished
    ON outbox_event (created_at) WHERE published_at IS NULL;

-- ---------------------------------------------------------------------
-- migrations/008_kyc_attempts.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- 008_kyc_attempts.sql
--
-- Counts failed KYC checks, so a customer whose check keeps failing is
-- set aside rather than retried forever.
--
-- The job takes the longest-waiting customers first. Without a count, one
-- whose check always fails stays at the front: enough of them would fill
-- every batch and nobody behind them would ever be checked. At
-- kyc.max-attempts the job stops picking the customer up. They stay
-- PENDING -- nothing was decided -- until someone fixes the cause and sets
-- attempts back to 0.
--
-- last_error holds the exception's class name only: a database error's
-- message can quote the customer's data back.
-- =====================================================================

ALTER TABLE kyc_verification
    ADD COLUMN IF NOT EXISTS attempts   INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_error TEXT    NULL;

-- ---------------------------------------------------------------------
-- migrations/009_bank_account.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- 009_bank_account.sql
--
-- The customer's one registered bank account. Money moves only between the
-- trading account and this bank account: deposits come from it, withdrawals
-- go to it, never anywhere else. It is given on the application and checked
-- by KYC before the customer can trade.
--
-- One per customer, keyed by client_id. The number is personal data: never
-- logged, and shown to the customer only masked (last four digits).
-- holder_name is the name the payout is addressed to -- the applicant's.
-- =====================================================================

CREATE TABLE IF NOT EXISTS bank_account (
    client_id       INTEGER       PRIMARY KEY
                                  REFERENCES client_account (client_id),
    account_number  VARCHAR(18)   NOT NULL,
    ifsc            CHAR(11)      NOT NULL,
    holder_name     VARCHAR(120)  NOT NULL,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),

    -- Indian account numbers run 9 to 18 digits; an IFSC is four letters
    -- for the bank, a zero, then six letters or digits for the branch.
    CONSTRAINT ck_bank_account_number CHECK (account_number ~ '^[0-9]{9,18}$'),
    CONSTRAINT ck_bank_account_ifsc   CHECK (ifsc ~ '^[A-Z]{4}0[A-Z0-9]{6}$')
);

-- ---------------------------------------------------------------------
-- migrations/010_payments.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- 010_payments.sql
--
-- Deposits and withdrawals through a payment gateway, recorded in the
-- fund_transfer table Sprint 3 already designed: direction DEPOSIT or
-- WITHDRAWAL, status PENDING -> SUCCESS or FAILED, one idempotency key per
-- client. This adds what deciding a transfer needs, as kyc_verification has:
-- why it failed, when it was decided, and a count of failed attempts so a
-- transfer whose processing keeps failing is set aside rather than retried
-- forever.
--
-- No CHECK ties reason or decided_at to status, unlike kyc_verification:
-- Sprint 3's seed inserts finished transfers without either, and seed files
-- run after migrations. The service writes them together.
-- =====================================================================

ALTER TABLE fund_transfer
    ADD COLUMN IF NOT EXISTS reason     TEXT        NULL,
    ADD COLUMN IF NOT EXISTS decided_at TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS attempts   INTEGER     NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_error TEXT        NULL;

-- The payment job reads only the PENDING ones, oldest first.
CREATE INDEX IF NOT EXISTS ix_fund_transfer_pending
    ON fund_transfer (created_at) WHERE status = 'PENDING';

-- ---------------------------------------------------------------------
-- migrations/011_preferences.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- 011_preferences.sql
--
-- Sprint 10, the preferences module (com.yellow.trade.preferences).
--
-- One row per customer, written the first time they save Settings. No row
-- means the documented defaults (decision log 0004): their own account,
-- the dashboard, and email. The contact detail is NOT here: email goes to
-- client_profile.email, read when a message is sent (decision log 0003).
--
-- default_account_id must be the customer's own; with one account per
-- login that is client_id, and the CHECK says so rather than trusting the
-- service alone.
-- =====================================================================

CREATE TABLE IF NOT EXISTS pref_preference (
    client_id          INTEGER     PRIMARY KEY
                                   REFERENCES client_account (client_id),
    default_account_id INTEGER     NOT NULL
                                   REFERENCES client_account (client_id),
    landing_screen     VARCHAR(20) NOT NULL,
    alert_channel      VARCHAR(10) NOT NULL,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_pref_landing_screen
        CHECK (landing_screen IN ('dashboard', 'orders', 'holdings', 'market-watch')),
    CONSTRAINT ck_pref_alert_channel
        CHECK (alert_channel IN ('EMAIL', 'IN_APP')),
    CONSTRAINT ck_pref_default_account_is_own
        CHECK (default_account_id = client_id)
);

-- ---------------------------------------------------------------------
-- migrations/012_notifications.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- 012_notifications.sql
--
-- Sprint 10, the notifications module (com.yellow.trade.notifications).
--
-- The ledger. One row per message a customer is owed: recorded QUEUED
-- before the Kafka offset is committed, then SENT or FAILED by the
-- dispatcher (decision log 0006). The channel and the destination are
-- filled in when it is sent, from the preferences module at that moment,
-- so they are null while a row waits.
--
-- The key is the event the message is about and, for a price alert, the
-- alert: one quote can cross several customers' alerts, and each of them
-- is owed its own message, but the same quote delivered twice for the
-- same alert is owed nothing more. NULLS NOT DISTINCT makes a trade event
-- (no alert) unique on its event id alone.
--
-- The destination is stored masked, never the address in full.
-- =====================================================================

CREATE TABLE IF NOT EXISTS notif_notification (
    notification_id UUID          PRIMARY KEY,
    event_id        UUID          NOT NULL,
    alert_id        BIGINT        NULL,
    client_id       INTEGER       NOT NULL REFERENCES client_account (client_id),
    kind            VARCHAR(20)   NOT NULL,
    subject         VARCHAR(200)  NOT NULL,
    body            VARCHAR(2000) NOT NULL,
    status          VARCHAR(10)   NOT NULL DEFAULT 'QUEUED',
    channel         VARCHAR(10)   NULL,
    destination     VARCHAR(320)  NULL,
    attempts        INTEGER       NOT NULL DEFAULT 0,
    last_error      VARCHAR(500)  NULL,
    next_attempt_at TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    sent_at         TIMESTAMPTZ   NULL,
    read_at         TIMESTAMPTZ   NULL,

    CONSTRAINT uq_notif_source UNIQUE NULLS NOT DISTINCT (event_id, alert_id),
    CONSTRAINT ck_notif_kind
        CHECK (kind IN ('ORDER_FILLED', 'ORDER_REJECTED', 'ORDER_CANCELLED', 'PRICE_ALERT')),
    CONSTRAINT ck_notif_status
        CHECK (status IN ('QUEUED', 'SENT', 'FAILED')),
    CONSTRAINT ck_notif_channel
        CHECK (channel IS NULL OR channel IN ('EMAIL', 'IN_APP')),
    -- Only a price alert names an alert, and every price alert does.
    CONSTRAINT ck_notif_alert
        CHECK ((kind = 'PRICE_ALERT') = (alert_id IS NOT NULL)),
    -- Sent means it went somewhere: the channel is known.
    CONSTRAINT ck_notif_sent_has_channel
        CHECK (status <> 'SENT' OR (channel IS NOT NULL AND sent_at IS NOT NULL))
);

-- The inbox: one account's notifications, newest first.
CREATE INDEX IF NOT EXISTS ix_notif_client_created
    ON notif_notification (client_id, created_at DESC);

-- The dispatcher: what is still waiting, oldest due first.
CREATE INDEX IF NOT EXISTS ix_notif_queued
    ON notif_notification (next_attempt_at) WHERE status = 'QUEUED';

-- ---------------------------------------------------------------------
-- migrations/013_watchlists.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- 013_watchlists.sql
--
-- Sprint 10, the watchlists module (com.yellow.trade.watchlists).
--
-- Watchlists a customer names and fills, price alerts they set, and the
-- latest price market-data has carried for each instrument. Instruments are
-- referenced by key, never copied: a symbol is resolved through the
-- platform's instrument tables.
--
-- watch_polled_symbols is this module's one published surface outside the
-- Trade REST API: the executor's poller reads it, so a stock somebody only
-- watches, or has an alert on, is priced too (decision log 0009).
-- =====================================================================

CREATE TABLE IF NOT EXISTS watch_list (
    watchlist_id BIGSERIAL    PRIMARY KEY,
    client_id    INTEGER      NOT NULL REFERENCES client_account (client_id),
    name         VARCHAR(40)  NOT NULL,
    position     INTEGER      NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_watch_list_name CHECK (length(btrim(name)) > 0)
);

CREATE INDEX IF NOT EXISTS ix_watch_list_client ON watch_list (client_id, position);

CREATE TABLE IF NOT EXISTS watch_item (
    watchlist_id  BIGINT      NOT NULL REFERENCES watch_list (watchlist_id) ON DELETE CASCADE,
    instrument_id INTEGER     NOT NULL REFERENCES instrument (instrument_id),
    position      INTEGER     NOT NULL,
    added_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (watchlist_id, instrument_id)
);

CREATE TABLE IF NOT EXISTS watch_alert (
    alert_id        BIGSERIAL     PRIMARY KEY,
    client_id       INTEGER       NOT NULL REFERENCES client_account (client_id),
    instrument_id   INTEGER       NOT NULL REFERENCES instrument (instrument_id),
    direction       VARCHAR(5)    NOT NULL,
    threshold       NUMERIC(18,4) NOT NULL,
    status          VARCHAR(10)   NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    triggered_at    TIMESTAMPTZ   NULL,
    triggered_price NUMERIC(18,4) NULL,
    -- The notification its firing queued, in the notifications module. A
    -- key, not a foreign key: that table is another module's.
    notification_id UUID          NULL,

    CONSTRAINT ck_watch_alert_direction CHECK (direction IN ('ABOVE', 'BELOW')),
    CONSTRAINT ck_watch_alert_status    CHECK (status IN ('ACTIVE', 'TRIGGERED', 'CANCELLED')),
    CONSTRAINT ck_watch_alert_threshold CHECK (threshold > 0),
    -- Triggered means it fired: when, at what price, and what it queued.
    CONSTRAINT ck_watch_alert_triggered
        CHECK (status <> 'TRIGGERED'
               OR (triggered_at IS NOT NULL AND triggered_price IS NOT NULL AND notification_id IS NOT NULL))
);

-- The hot path: every quote asks which ACTIVE alerts on its instrument it
-- crosses. Only active alerts are indexed, so a customer's history of fired
-- and cancelled ones costs the consumer nothing.
CREATE INDEX IF NOT EXISTS ix_watch_alert_active
    ON watch_alert (instrument_id, direction, threshold) WHERE status = 'ACTIVE';

CREATE INDEX IF NOT EXISTS ix_watch_alert_client ON watch_alert (client_id, created_at DESC);

-- The latest quote market-data carried for an instrument: one row each,
-- replaced only by a quote observed later than the one it holds.
CREATE TABLE IF NOT EXISTS watch_latest_quote (
    instrument_id  INTEGER       PRIMARY KEY REFERENCES instrument (instrument_id),
    price          NUMERIC(18,4) NOT NULL,
    change_percent NUMERIC(12,4) NULL,
    stale          BOOLEAN       NOT NULL,
    quote_as_of    TIMESTAMPTZ   NOT NULL,
    event_id       UUID          NOT NULL,
    received_at    TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- What the executor's poller adds to its own set: every instrument on a
-- watchlist, and every one with an alert waiting to fire.
CREATE OR REPLACE VIEW watch_polled_symbols AS
SELECT DISTINCT i.instrument_id, COALESCE(e.ticker, m.scheme_code) AS symbol
FROM (SELECT instrument_id FROM watch_item
      UNION
      SELECT instrument_id FROM watch_alert WHERE status = 'ACTIVE') watched
JOIN instrument i       ON i.instrument_id = watched.instrument_id
LEFT JOIN equity e      ON e.instrument_id = i.instrument_id
LEFT JOIN mutual_fund m ON m.instrument_id = i.instrument_id;

-- ---------------------------------------------------------------------
-- migrations/014_portfolio.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- 014_portfolio.sql
--
-- Sprint 10, the portfolio module (com.yellow.trade.portfolio).
--
-- Realised profit and loss, booked at the moment of each sale and never
-- recomputed (Contracts/API Schemas/portfolio-api.yaml; decision log 0011): one row per
-- sale, from the ORDER_FILLED event trade-events carried for it, booked only
-- for a sell the platform's own orders table recorded as filled.
--
-- realised = (sale price - average cost at the sale) * quantity sold.
-- Nothing about today's price is here. Positions, cash and prices are read
-- from where they live; this module writes nothing but this table.
-- =====================================================================

CREATE TABLE IF NOT EXISTS pf_realised (
    event_id      UUID          PRIMARY KEY,
    order_id      UUID          NOT NULL UNIQUE,
    client_id     INTEGER       NOT NULL REFERENCES client_account (client_id),
    instrument_id INTEGER       NOT NULL REFERENCES instrument (instrument_id),
    symbol        VARCHAR(30)   NOT NULL,
    quantity      NUMERIC(18,6) NOT NULL,
    sale_price    NUMERIC(18,4) NOT NULL,
    average_cost  NUMERIC(18,4) NOT NULL,
    realised      NUMERIC(18,4) NOT NULL,
    booked_at     TIMESTAMPTZ   NOT NULL,
    recorded_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT ck_pf_realised_quantity CHECK (quantity > 0),
    -- The arithmetic is the contract's, and the row says so.
    CONSTRAINT ck_pf_realised_sum CHECK (realised = round((sale_price - average_cost) * quantity, 4))
);

-- An account's realised figure, over a range of days.
CREATE INDEX IF NOT EXISTS ix_pf_realised_client ON pf_realised (client_id, booked_at);

-- ---------------------------------------------------------------------
-- migrations/015_strategy.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- 015_strategy.sql
--
-- Sprint 10, the strategy module (com.yellow.trade.strategy), a stretch
-- extension.
--
-- A strategy is a rule a customer sets once: buy a quantity when the price
-- falls to a level, or sell when it rises to one. The platform places the
-- order through POST /api/v1/orders with a token auth mints for the
-- account (decision log 0012). Every firing and every refusal is a run.
--
-- Bounded here as well as in code: a positive quantity, spend and
-- position, and a status that only the firing transaction moves.
-- strat_polled_symbols is the module's surface to the executor's poller:
-- a stock with an armed strategy is priced even if nobody holds it.
-- =====================================================================

CREATE TABLE IF NOT EXISTS strat_strategy (
    strategy_id   BIGSERIAL     PRIMARY KEY,
    client_id     INTEGER       NOT NULL REFERENCES client_account (client_id),
    instrument_id INTEGER       NOT NULL REFERENCES instrument (instrument_id),
    side          VARCHAR(4)    NOT NULL,
    quantity      INTEGER       NOT NULL,
    trigger_kind  VARCHAR(13)   NOT NULL,
    trigger_price NUMERIC(18,4) NOT NULL,
    max_spend     NUMERIC(18,4) NOT NULL,
    max_position  INTEGER       NOT NULL,
    enabled       BOOLEAN       NOT NULL DEFAULT false,
    status        VARCHAR(7)    NOT NULL DEFAULT 'ARMED',
    failures      INTEGER       NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    last_fired_at TIMESTAMPTZ   NULL,

    CONSTRAINT ck_strat_side      CHECK (side IN ('BUY', 'SELL')),
    CONSTRAINT ck_strat_trigger   CHECK (trigger_kind IN ('FALLS_THROUGH', 'RISES_THROUGH')),
    CONSTRAINT ck_strat_status    CHECK (status IN ('ARMED', 'FIRED', 'STOPPED')),
    CONSTRAINT ck_strat_positive  CHECK (quantity > 0 AND trigger_price > 0 AND max_spend > 0 AND max_position > 0),
    CONSTRAINT ck_strat_failures  CHECK (failures BETWEEN 0 AND 3)
);

-- The hot path: which armed, enabled strategies a quote for this instrument could fire.
CREATE INDEX IF NOT EXISTS ix_strat_armed
    ON strat_strategy (instrument_id, trigger_kind, trigger_price) WHERE enabled AND status = 'ARMED';

CREATE INDEX IF NOT EXISTS ix_strat_client ON strat_strategy (client_id, created_at DESC);

CREATE TABLE IF NOT EXISTS strat_run (
    run_id          BIGSERIAL     PRIMARY KEY,
    strategy_id     BIGINT        NOT NULL REFERENCES strat_strategy (strategy_id) ON DELETE CASCADE,
    at              TIMESTAMPTZ   NOT NULL DEFAULT now(),
    quote_price     NUMERIC(18,4) NULL,
    outcome         VARCHAR(13)   NOT NULL,
    reason          VARCHAR(300)  NULL,
    -- The order a firing placed, on the platform's orders table.
    order_id        UUID          NULL,
    -- The market-data quote or trade-events event this run came from: a
    -- replay of either finds it here and does nothing twice.
    source_event_id UUID          NOT NULL,

    CONSTRAINT uq_strat_run_source UNIQUE (strategy_id, source_event_id),
    CONSTRAINT ck_strat_run_outcome
        CHECK (outcome IN ('PLACED', 'FILLED', 'REJECTED', 'REFUSED_LIMIT', 'FAILED', 'STOPPED'))
);

CREATE INDEX IF NOT EXISTS ix_strat_run_strategy ON strat_run (strategy_id, at DESC);
CREATE INDEX IF NOT EXISTS ix_strat_run_order ON strat_run (order_id) WHERE order_id IS NOT NULL;

-- What the executor's poller adds to its own set: every instrument an
-- enabled, armed strategy is waiting on.
CREATE OR REPLACE VIEW strat_polled_symbols AS
SELECT DISTINCT instrument_id
FROM strat_strategy
WHERE enabled AND status = 'ARMED';

-- ---------------------------------------------------------------------
-- migrations/016_strategy_indicators.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- 016_strategy_indicators.sql
--
-- Sprint 10, the strategy module: the two indicator triggers the team's
-- acceptance criteria ask for (decision log 0017).
--
--   MA_CROSSOVER  a buy fires when the 20-day average crosses above the
--                 50-day; a sell when it crosses below.
--   BOLLINGER     a buy fires at the lower band, a sell at the upper.
--
-- Neither has a price of its own, so trigger_price is now NULL for them
-- and required for the two level triggers. Safe to run again: each
-- constraint is dropped, if it is there, before it is added.
-- =====================================================================

ALTER TABLE strat_strategy ALTER COLUMN trigger_price DROP NOT NULL;

ALTER TABLE strat_strategy DROP CONSTRAINT IF EXISTS ck_strat_trigger;
ALTER TABLE strat_strategy ADD CONSTRAINT ck_strat_trigger
    CHECK (trigger_kind IN ('FALLS_THROUGH', 'RISES_THROUGH', 'MA_CROSSOVER', 'BOLLINGER'));

ALTER TABLE strat_strategy DROP CONSTRAINT IF EXISTS ck_strat_positive;
ALTER TABLE strat_strategy ADD CONSTRAINT ck_strat_positive
    CHECK (quantity > 0 AND max_spend > 0 AND max_position > 0 AND (trigger_price IS NULL OR trigger_price > 0));

-- A level trigger has a price; an indicator trigger has none.
ALTER TABLE strat_strategy DROP CONSTRAINT IF EXISTS ck_strat_trigger_price;
ALTER TABLE strat_strategy ADD CONSTRAINT ck_strat_trigger_price
    CHECK ((trigger_kind IN ('FALLS_THROUGH', 'RISES_THROUGH')) = (trigger_price IS NOT NULL));

-- ---------------------------------------------------------------------
-- indexes/001_performance_indexes.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- 002_performance_indexes.sql
-- =====================================================================

-- Order book / "my orders" screen: a client's orders, newest first.
CREATE INDEX IF NOT EXISTS ix_orders_client_placed
    ON orders (client_id, date_placed DESC);

-- The black box poller and the EOD archival job both scan by status.
CREATE INDEX IF NOT EXISTS ix_orders_status
    ON orders (status);

-- Past-orders report, same access pattern as the live screen.
CREATE INDEX IF NOT EXISTS ix_orders_history_client_placed
    ON orders_history (client_id, date_placed DESC);

-- Portfolio screen: every position for one client.
CREATE INDEX IF NOT EXISTS ix_position_client
    ON position (client_id);

-- Funds / statement screen: a client's transfers, newest first.
CREATE INDEX IF NOT EXISTS ix_fund_transfer_client_created
    ON fund_transfer (client_id, created_at DESC);


-- Instrument search excludes delisted scrips. Partial index: only
-- tradable rows are indexed, so it stays small as delistings accumulate.
CREATE INDEX IF NOT EXISTS ix_instrument_tradable
    ON instrument (is_tradable)
    WHERE is_tradable;
