#!/usr/bin/env bash
# =====================================================================
# Rebuilds Databases/PostgreSQL/schema.sql and seed_data.sql from the
# ordered source files, so the two single-file scripts never drift from
# the migrations they are made of.
#
#   schema.sql     base/ + migrations/ (in number order) + indexes/
#   seed_data.sql  seed/ (in number order)
#
# Run it after adding a migration or a seed file, then commit both outputs.
# =====================================================================
set -euo pipefail

DB="$(cd "$(dirname "${BASH_SOURCE[0]}")/../Databases/PostgreSQL" && pwd)"

concat() {
    local out="$1" title="$2"; shift 2
    {
        echo "-- ====================================================================="
        echo "-- ${title}"
        echo "--"
        echo "-- GENERATED by scripts/build-db-scripts.sh from the files named below,"
        echo "-- in this order. Edit those, not this file, then run the script again."
        echo "-- ====================================================================="
        for f in "$@"; do
            echo
            echo "-- ---------------------------------------------------------------------"
            echo "-- ${f#"$DB"/}"
            echo "-- ---------------------------------------------------------------------"
            cat "$f"
        done
    } > "$out"
    echo "wrote ${out#"$DB"/} from $# files"
}

# One phase at a time: ls sorts all its arguments together, which would put
# indexes/ before migrations/.
schema=()
for phase in base migrations indexes; do
    mapfile -t files < <(LC_ALL=C ls "$DB/$phase"/*.sql)
    schema+=("${files[@]}")
done
mapfile -t seeds < <(LC_ALL=C ls "$DB"/seed/*.sql)

concat "$DB/schema.sql" "schema.sql - the trading_system_db schema: tables, migrations 001-016, indexes" "${schema[@]}"
concat "$DB/seed_data.sql" "seed_data.sql - reference data and demo data for trading_system_db" "${seeds[@]}"
